sudo: true
dist: trusty
language: cpp
compiler:
 - clang
 - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - cmake
      - cmake-data

os:
  - linux

install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=RelWithDebInfo

before_script:
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - make all
