sudo: true
dist: trusty
language: cpp
compiler:
 - clang
 - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data

os:
  - linux

before_install:
  - wget http://llvm.org/releases/3.6.0/clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $HOME/clang+llvm.tar.xz
  - mkdir $HOME/clang-3.6.0
  - tar xf $HOME/clang+llvm.tar.xz -C $HOME/clang-3.6.0 --strip-components 1

install:
  - if [ "$CXX" = "clang++" ]; then export CXX="$HOME/clang-3.6.0/bin/clang++" CC="clang-3.6"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

env:
  - CPPFLAGS="-I $HOME/clang-3.6.0/include/c++/v1"
  - CXXFLAGS=-lc++
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=RelWithDebInfo

before_script:
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - make all
