sudo: true
dist: trusty
language: cpp
compiler:
 - clang
 - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data
      - xorg-dev
      - libglu1-mesa-dev
      - mesa-common-dev

os:
  - linux

env:
  global:
    - CLANG_VERSION=3.8.0
    - CLANG_ARCHIVE=$HOME/clang+llvm.tar.xz
    - CLANG_DIR=$HOME/clang-$CLANG_VERSION

  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
    - BUILD_TYPE=RelWithDebInfo

before_install:
  - if [ "$CXX" = "clang++" ]; then wget http://llvm.org/releases/$CLANG_VERSION/clang+llvm-$CLANG_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $CLANG_ARCHIVE && mkdir $CLANG_DIR && tar xf $CLANG_ARCHIVE -C $CLANG_DIR --strip-components 1; fi
  - if [ "$CXX" = "clang++" ]; then export CPPFLAGS="-I $CLANG_DIR/include/c++/v1"; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-lc++ -lc++abi -L$CLANG_DIR/lib"; fi
  - if [ "$CXX" = "clang++" ]; then export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$CLANG_DIR/lib"; fi

install:
  - if [ "$CXX" = "clang++" ]; then export CXX="$CLANG_DIR/bin/clang++" CC="$CLANG_DIR/bin/clang"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - make all
