if (BUILD_EXAMPLES)
  hunter_config(libigl
    GIT_SUBMODULE "Dependencies/libigl"
    CMAKE_ARGS
      HUNTER_ENABLED=ON
      LIBIGL_USE_STATIC_LIBRARY=OFF
      LIBIGL_WITH_ANTTWEAKBAR=OFF
      LIBIGL_WITH_CGAL=OFF
      LIBIGL_WITH_COMISO=OFF
      LIBIGL_WITH_CORK=OFF
      LIBIGL_WITH_EMBREE=OFF
      LIBIGL_WITH_LIM=OFF
      LIBIGL_WITH_MATLAB=OFF
      LIBIGL_WITH_MOSEK=OFF
      LIBIGL_WITH_OPENGL=OFF
      LIBIGL_WITH_OPENGL_GLFW=OFF
      LIBIGL_WITH_OPENGL_GLFW_IMGUI=OFF
      LIBIGL_WITH_PNG=OFF
      LIBIGL_WITH_PYTHON=OFF
      LIBIGL_WITH_TETGEN=OFF
      LIBIGL_WITH_TRIANGLE=OFF
      LIBIGL_WITH_VIEWER=OFF
      LIBIGL_WITH_XML=OFF
  )
endif()

