cmake_minimum_required(VERSION 3.2 FATAL_ERROR)

add_library(GSL INTERFACE IMPORTED)

if (APPLE)
  set_property(TARGET GSL PROPERTY INTERFACE_COMPILE_OPTIONS
    -isystem${DEPENDENCIES_DIR}/GSL/include
  )
else()
  set_property(TARGET GSL PROPERTY INTERFACE_INCLUDE_DIRECTORIES
    ${DEPENDENCIES_DIR}/GSL/include
  )
endif()
